#!/usr/bin/env node

// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

if(process.argv[2] !== 'get'){
  process.stderr.write('missing first argument. must be "get"\n')
  process.exit(1)
}

let bufs = []
process.stdin.on('data',(b)=>bufs.push(b))
.on('end',()=>{
  process.stdout.write(JSON.stringify({Username:"_bork",Secret:(Buffer.concat(bufs)+'').trim()})+"\n")
})

